"""Custom SAR IsaacLab environment specs and hyperparameter presets.

Separated from ``_isaaclab_registry.py`` (auto-generated by
``scripts/sync_isaaclab_envs.py``) so that entries here are not
overwritten when the sync script regenerates the upstream registry.

Merged into ``ENV_REGISTRY`` and ``ZOO_PRESETS`` by ``env_spec.py``
and ``hp_presets.py`` respectively.
"""

from __future__ import annotations

from typing import Any

from p2p.training.env_spec import EnvSpec

# ---------------------------------------------------------------------------
# Environment specs
# ---------------------------------------------------------------------------

CUSTOM_ISAACLAB_ENV_SPECS: dict[str, EnvSpec] = {
    "Isaac-Spin-Pen-Shadow-Direct-v0": EnvSpec(
        env_id="Isaac-Spin-Pen-Shadow-Direct-v0",
        name="Spin-Pen-Shadow-Direct",
        obs_dim=157,
        action_dim=20,
        info_keys={"episode_reward": "cumulative reward"},
        description="Dexterous (Pen Spinning)",
        engine="isaaclab",
    ),
    # Eureka benchmark envs — dims from Isaac Lab 2.1 source configs.
    "Isaac-Repose-Cube-Allegro-Direct-v0": EnvSpec(
        env_id="Isaac-Repose-Cube-Allegro-Direct-v0",
        name="Repose-Cube-Allegro-Direct",
        obs_dim=124,
        action_dim=16,
        info_keys={"episode_reward": "cumulative reward"},
        description="Dexterous",
        engine="isaaclab",
    ),
    "Isaac-Repose-Cube-Shadow-Direct-v0": EnvSpec(
        env_id="Isaac-Repose-Cube-Shadow-Direct-v0",
        name="Repose-Cube-Shadow-Direct",
        obs_dim=157,
        action_dim=20,
        info_keys={"episode_reward": "cumulative reward"},
        description="Dexterous",
        engine="isaaclab",
    ),
    "Isaac-Franka-Cabinet-Direct-v0": EnvSpec(
        env_id="Isaac-Franka-Cabinet-Direct-v0",
        name="Franka-Cabinet-Direct",
        obs_dim=23,
        action_dim=9,
        info_keys={"episode_reward": "cumulative reward"},
        description="Manipulation",
        engine="isaaclab",
    ),
}

# ---------------------------------------------------------------------------
# Zoo hyperparameter presets
# ---------------------------------------------------------------------------

_DEFAULT_DEXTEROUS_PRESET: dict[str, Any] = {
    "_zoo_n_envs": 4096,
    "learning_rate": 0.001,
    "num_steps": 24,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "update_epochs": 5,
    "clip_coef": 0.2,
    "ent_coef": 0.01,
    "vf_coef": 1.0,
    "max_grad_norm": 1.0,
    "num_minibatches": 4,
    "net_arch": [256, 256],
    "normalize_obs": True,
    "normalize_reward": True,
}

CUSTOM_ISAACLAB_PRESETS: dict[str, dict[str, Any]] = {
    # Same baseline as other Shadow Hand envs; not yet tuned for pen geometry.
    "Isaac-Spin-Pen-Shadow-Direct-v0": {**_DEFAULT_DEXTEROUS_PRESET},
    # Allegro and Shadow Repose presets match auto-generated defaults — no override needed.
    # Franka Cabinet: override learning_rate and num_steps (auto-gen has different values).
    "Isaac-Franka-Cabinet-Direct-v0": {
        **_DEFAULT_DEXTEROUS_PRESET,
        "learning_rate": 0.0005,
        "num_steps": 16,
    },
}
